version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.0.0

    steps:
      - checkout # check out the code in the project directory
      - run: yarn install
      - run: yarn lint
      - run: yarn verify-test
      - run: yarn test
